/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package musicplayer;

/**
 *
 * @author Bruno
 */
public enum EnumGeneros {
  BLUES,  CLASSIC_ROCK, COUNTRY, DANCE , DISCO, FUNK, GRUNGE, HIPHOP, JAZZ, METAL, NEW_AGE, OLDIES,
  OTHER, POP, RHYTHM_AND_BLUES, RAP, REGGAE, ROCK, TECHNO, INDUSTRIAL, ALTERNATIVE, SKA, DEATH_METAL,
  PRANKS, SOUNDTRACK, EURO_TECHNO, AMBIENT, TRIP_HOP, VOCAL, JAZZ_AND_FUNK, FUSION, TRANCE, CLASSICAL,
  INSTRUMENTAL, ACID, HOUSE, GAME, SOUND_CLIP, GOSPEL, NOISE, ALTERNATIVE_ROCK, BASS, SOUL, PUNK,
  SPACE, MEDITATIVE, INSTRUMENTAL_POP, INSTRUMENTAL_ROCK, ETHNIC, GOTHIC, DARKWAVE, TECHNO_INDUSTRIAL,
  ELECTRONIC, POP_FOLK, EURODANCE, DREAM, SOUTHERN_ROCK, COMEDY, CULT, GANGSTA, TOP_40, CHRISTIAN_RAP,
  POP_FUNK, JUNGLE, NATIVE_US, CABARET, NEW_WAVE, PSYCHEDELIC, RAVE, SHOWTUNES, TRAILER, LO_FI, TRIBAL,
  ACID_PUNK, ACID_JAZZ, POLKA, RETRO, MUSICAL, ROCK_N_ROLL, HARD_ROCK
}
